# Openstax oauth
OPENSTAX_BACKEND_CLIENT_ID = 'SET-ME-PLEASE'
OPENSTAX_BACKEND_CLIENT_SECRET = 'SET-ME-PLEASE'

# Rover oauth
ROVERBYOPENSTAX_BACKEND_CLIENT_ID = 'SET-ME-PLEASE'
ROVERBYOPENSTAX_BACKEND_CLIENT_SECRET = 'SET-ME-PLEASE'

# Willo Labs LTI key
WILLO_API_AUTHORIZATION_TOKEN = 'SET-ME-PLEASE'

