# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-18 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_creators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, help_text='True if this is the current campaign to which new salesforce contacts should be added.')),
                ('name', models.CharField(max_length=50)),
                ('salesforce_id', models.CharField(blank=True, default=None, help_text='Example: 7010m0000002pARAAY from the following URL: https://cs65.lightning.force.com/lightning/r/Campaign/7010m0000002pARAAY/view', max_length=50, null=True)),
            ],
            options={
                'ordering': ['active'],
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('dev', 'Development'), ('test', 'Testing / QA'), ('prod', 'Production')], default='dev', help_text='Type of Open edX environment in which this configuration will be used.', max_length=24, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email_notification', models.EmailField(help_text='Email address for notifications: errors, completed operations.', max_length=254)),
                ('url', models.URLField(help_text='salesforce api account login URL.', max_length=255)),
                ('username', models.CharField(help_text='salesforce api account username.', max_length=255)),
                ('password', models.CharField(help_text='salesforce api account password.', max_length=255)),
                ('security_token', models.CharField(help_text='salesforce api security token.', max_length=255)),
                ('sandbox', models.BooleanField(default=True, help_text='True if you want this configuration to connect to the salesforce api Sandbox instead of the production data store.')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesforce.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='course_creators.CourseCreator')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('real_course_created_at', models.DateTimeField(blank=True, null=True)),
                ('contact_id', models.CharField(blank=True, max_length=50, null=True)),
                ('salesforce_push_pending', models.BooleanField(default=True)),
                ('completed_training_wheels_date', models.DateTimeField(blank=True, null=True)),
                ('started_assignment_date', models.DateTimeField(blank=True, null=True)),
                ('completed_assignment_date', models.DateTimeField(blank=True, null=True)),
                ('soft_ask_decision', models.CharField(blank=True, max_length=255, null=True)),
                ('soft_ask_decision_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_enrollment', models.IntegerField(blank=True, null=True)),
                ('latest_adoption_decision', models.CharField(blank=True, max_length=255, null=True)),
                ('completed_am_page_tips', models.DateTimeField(blank=True, null=True)),
                ('completed_building_assignments_training', models.DateTimeField(blank=True, null=True)),
                ('completed_how_to_set_up_grading_page_tip', models.DateTimeField(blank=True, null=True)),
                ('completed_super_training_wheel_1', models.DateTimeField(blank=True, null=True)),
                ('created_a_course', models.DateTimeField(blank=True, null=True)),
                ('downloaded_gsg', models.DateTimeField(blank=True, null=True)),
                ('watched_video', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesforce.Campaign')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
