# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-18 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0002_auto_20190617_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Completed_AM_page_tips',
            new_name='completed_am_page_tips',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Completed_building_assignments_training',
            new_name='completed_building_assignments_training',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Completed_how_to_set_up_grading_page_tip',
            new_name='completed_how_to_set_up_grading_page_tip',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Completed_super_training_wheel_1',
            new_name='completed_super_training_wheel_1',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Created_a_course',
            new_name='created_a_course',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Downloaded_GSG',
            new_name='downloaded_gsg',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Watched_video',
            new_name='watched_video',
        ),
    ]
