# Generated by Django 2.2.13 on 2020-08-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0002_contact_lms_completed_assignment_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='salesforce_push_pending',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
