# Generated by Django 2.2.13 on 2020-08-04 19:55

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(default=None, help_text='Rover Course Key (Opaque Key). Based on Institution, Course, Section identifiers. Example: course-v1:edX+DemoX+Demo_Course', max_length=255, primary_key=True, serialize=False)),
                ('payment_deadline_date', models.DateTimeField(blank=True, help_text='The date after which the paywall will rise for enrolled students who have not yet paid.', null=True)),
            ],
            options={
                'verbose_name_plural': 'Rover E-Commerce Configurations',
                'verbose_name': 'Rover E-Commerce Configuration',
            },
        ),
        migrations.CreateModel(
            name='EOPWhitelist',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Rover Ecommerce EOP Students',
                'verbose_name': 'Rover Ecommerce EOP Student',
            },
        ),
    ]
