# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-01 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('willolabs', '0005_ltiexternalcourse_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='context_label',
            field=models.CharField(blank=True, help_text=b'Example: willolabs-launch-test-ku-blackboard-rover-grade-testing', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='course_id',
            field=opaque_keys.edx.django.models.CourseKeyField(db_index=True, default=None, help_text=b'Rover Course Key (Opaque Key). Based on Institution, Course, Section identifiers. Example: course-v1:edX+DemoX+Demo_Course', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='custom_api_domain',
            field=models.CharField(blank=True, help_text=b'Example: willowlabs.instructure.com', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='custom_course_id',
            field=models.CharField(blank=True, help_text=b'Example: 421', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='custom_course_startat',
            field=models.DateTimeField(blank=True, help_text=b'Example: 2019-12-11 16:18:01 -0500', null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='custom_orig_context_id',
            field=models.CharField(blank=True, help_text=b'Context_id from the original source system (ie Canvas, Blackboard). Example: 9caf71ef12da4d2993f8929242d93922', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='custom_profile_url',
            field=models.URLField(blank=True, help_text=b'URL pointing to user profile in the original source system. Example: https://courseware.ku.edu/learn/api/v1/lti/profile?lti_version=LTI-1p0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='custom_tpa_next',
            field=models.URLField(blank=True, help_text=b'/account/finish_auth?course_id=course-v1%3AKU%2BOS9471721_108c%2BSpring2020_Fuka_Sample1&enrollment_action=enroll&email_opt_in=false', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='ext_wl_launch_key',
            field=models.CharField(blank=True, help_text=b'Example: QcTz6q', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='ext_wl_launch_url',
            field=models.URLField(blank=True, help_text=b'Example: https://stage.willolabs.com/launch/QcTz6q/8cmzcd', null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='ext_wl_outcome_service_url',
            field=models.URLField(blank=True, help_text=b'Example: https://stage.willolabs.com/api/v1/outcomes/QcTz6q/e14751571da04dd3a2c71a311dda2e1b/', null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='ext_wl_version',
            field=models.CharField(blank=True, help_text=b'Example: 1.0', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='tool_consumer_info_product_family_code',
            field=models.CharField(blank=True, help_text=b'Example: canvas', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='tool_consumer_info_version',
            field=models.CharField(blank=True, help_text=b'Example: cloud', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='tool_consumer_instance_contact_email',
            field=models.EmailField(blank=True, help_text=b'Example: notifications@instructure.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='tool_consumer_instance_description',
            field=models.CharField(blank=True, help_text=b'Example: The University of Kansas', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='tool_consumer_instance_guid',
            field=models.CharField(blank=True, help_text=b'Example: 7M58pE4F4Y56gZHUe6jaxhQ1csaktjA00ZiVNQb7:canvas-lms', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='tool_consumer_instance_name',
            field=models.CharField(blank=True, help_text=b'Example: Willo Labs', max_length=50, null=True),
        ),
    ]