# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-20 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_consumers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ltiexternalcourse',
            old_name='custom_canvas_api_domain',
            new_name='custom_api_domain',
        ),
        migrations.RenameField(
            model_name='ltiexternalcourse',
            old_name='custom_canvas_course_id',
            new_name='custom_course_id',
        ),
        migrations.RenameField(
            model_name='ltiexternalcourse',
            old_name='custom_canvas_course_startat',
            new_name='custom_course_startat',
        ),
        migrations.RenameField(
            model_name='ltiexternalcourseenrollment',
            old_name='custom_canvas_person_timezone',
            new_name='custom_person_timezone',
        ),
        migrations.RenameField(
            model_name='ltiexternalcourseenrollment',
            old_name='custom_canvas_user_id',
            new_name='custom_user_id',
        ),
        migrations.RenameField(
            model_name='ltiexternalcourseenrollment',
            old_name='custom_canvas_user_login_id',
            new_name='custom_user_login_id',
        ),
        migrations.AddField(
            model_name='ltiexternalcourse',
            name='custom_orig_context_id',
            field=models.CharField(help_text=b'Context_id from the original source system (ie Canvas, Blackboard). Example: 9caf71ef12da4d2993f8929242d93922', max_length=50, null=True, verbose_name=b'custom_orig_context_id'),
        ),
        migrations.AddField(
            model_name='ltiexternalcourse',
            name='custom_profile_url',
            field=models.URLField(help_text=b'URL pointing to user profile in the original source system. Example: https://courseware.ku.edu/learn/api/v1/lti/profile?lti_version=LTI-1p0', max_length=50, null=True, verbose_name=b'custom_profile_url'),
        ),
        migrations.AddField(
            model_name='ltiexternalcourse',
            name='custom_tpa_next',
            field=models.URLField(help_text=b'/account/finish_auth?course_id=course-v1%3AKU%2BOS9471721_108c%2BSpring2020_Fuka_Sample1&enrollment_action=enroll&email_opt_in=false', max_length=255, null=True, verbose_name=b'LTI Params - custom_tpa_next'),
        ),
        migrations.AddField(
            model_name='ltiexternalcourse',
            name='tool_consumer_instance_description',
            field=models.CharField(help_text=b'Example: The University of Kansas', max_length=50, null=True, verbose_name=b'tool_consumer_instance_description'),
        ),
        migrations.AddField(
            model_name='ltiexternalcourseenrollment',
            name='lis_person_sourcedid',
            field=models.CharField(blank=True, default=None, help_text=b'Example: _tonn_test5', max_length=255, null=True, verbose_name=b'Source system Username'),
        ),
    ]
