# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-27 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_consumers', '0002_auto_20200220_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ltiexternalcourse',
            options={'verbose_name': 'LTI External Course'},
        ),
        migrations.AlterModelOptions(
            name='ltiexternalcourseenrollment',
            options={'verbose_name': 'LTI External Course Enrollment'},
        ),
        migrations.AlterModelOptions(
            name='ltiexternalcourseenrollmentgrades',
            options={'verbose_name': 'LTI External Course Enrollment Grades'},
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='context_id',
            field=models.CharField(help_text=b"This is the unique identifier of the Willo Labs integration, passed viafrom tpa-lti-params. Course runs from external LMS' are intended to be unique.Example: e14751571da04dd3a2c71a311dda2e1b", max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='context_label',
            field=models.CharField(help_text=b'Example: lti_consumers-launch-test-ku-blackboard-rover-grade-testing', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='context_title',
            field=models.CharField(blank=True, default=None, help_text=b'Name of the Willo Lab integration. Example: Willo Labs Test Launch for KU Blackboard Rover Grade Testing', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='course_id',
            field=opaque_keys.edx.django.models.CourseKeyField(blank=True, db_index=True, default=None, help_text=b'Rover Course Key (Opaque Key). Based on Institution, Course, Section identifiers. Example: course-v1:edX+DemoX+Demo_Course', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='custom_api_domain',
            field=models.CharField(help_text=b'Example: willowlabs.instructure.com', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='custom_course_id',
            field=models.CharField(help_text=b'Example: 421', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='custom_course_startat',
            field=models.DateTimeField(help_text=b'Example: 2019-12-11 16:18:01 -0500', null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='custom_orig_context_id',
            field=models.CharField(help_text=b'Context_id from the original source system (ie Canvas, Blackboard). Example: 9caf71ef12da4d2993f8929242d93922', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='custom_profile_url',
            field=models.URLField(help_text=b'URL pointing to user profile in the original source system. Example: https://courseware.ku.edu/learn/api/v1/lti/profile?lti_version=LTI-1p0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='custom_tpa_next',
            field=models.URLField(help_text=b'/account/finish_auth?course_id=course-v1%3AKU%2BOS9471721_108c%2BSpring2020_Fuka_Sample1&enrollment_action=enroll&email_opt_in=false', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='ext_wl_launch_key',
            field=models.CharField(help_text=b'Example: QcTz6q', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='ext_wl_launch_url',
            field=models.URLField(help_text=b'Example: https://stage.lti_consumers.com/launch/QcTz6q/8cmzcd', null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='ext_wl_outcome_service_url',
            field=models.URLField(help_text=b'Example: https://stage.lti_consumers.com/api/v1/outcomes/QcTz6q/e14751571da04dd3a2c71a311dda2e1b/', null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='ext_wl_version',
            field=models.CharField(help_text=b'Example: 1.0', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='tool_consumer_info_product_family_code',
            field=models.CharField(help_text=b'Example: canvas', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='tool_consumer_info_version',
            field=models.CharField(help_text=b'Example: cloud', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='tool_consumer_instance_contact_email',
            field=models.EmailField(help_text=b'Example: notifications@instructure.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='tool_consumer_instance_description',
            field=models.CharField(help_text=b'Example: The University of Kansas', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='tool_consumer_instance_guid',
            field=models.CharField(help_text=b'Example: 7M58pE4F4Y56gZHUe6jaxhQ1csaktjA00ZiVNQb7:canvas-lms', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourse',
            name='tool_consumer_instance_name',
            field=models.CharField(help_text=b'Example: Willo Labs', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourseassignmentproblems',
            name='usage_key',
            field=opaque_keys.edx.django.models.UsageKeyField(help_text=b'Open edX Block usage key pointing to the homework problem that was graded, invoking the post_grades() api. Example: block-v1:ABC+OS9471721_9626+01+type@swxblock+block@c081d7653af211e98379b7d76f928163', max_length=255),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourseassignments',
            name='display_name',
            field=models.CharField(help_text=b'Title text of the Rover assignment. Example: Chapter 5 Section 1 Quadratic Functions Sample Homework', max_length=255),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourseassignments',
            name='url',
            field=models.URLField(help_text=b'Open edX Course Assignment', max_length=255),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourseenrollment',
            name='custom_person_timezone',
            field=models.CharField(blank=True, default=None, help_text=b"Source system time zone from user's profile, provided to Willo Labs. Example: America/New_York", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourseenrollment',
            name='custom_user_id',
            field=models.CharField(blank=True, default=None, help_text=b'User ID provided to Willo Labs. Example: 394', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourseenrollment',
            name='custom_user_login_id',
            field=models.CharField(blank=True, default=None, help_text=b'Login ID provided to Willo Labs. Example: rover_student', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourseenrollment',
            name='ext_roles',
            field=models.CharField(blank=True, default=None, help_text=b'User permitted roles in external system. Example: urn:lti:instrole:ims/lis/Student,urn:lti:role:ims/lis/Learner,urn:lti:sysrole:ims/lis/User', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourseenrollment',
            name='ext_wl_privacy_mode',
            field=models.CharField(blank=True, default=None, help_text=b'Privacy settings from external system, provided to Willo Lab. Example: allow-pii-all', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourseenrollment',
            name='lis_person_contact_email_primary',
            field=models.EmailField(help_text=b'Example: rover_student@lti_consumers.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourseenrollment',
            name='lis_person_name_family',
            field=models.CharField(blank=True, default=None, help_text=b'Example: Thornton', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourseenrollment',
            name='lis_person_name_full',
            field=models.CharField(blank=True, default=None, help_text=b'Example: Billy Bob Thornton', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourseenrollment',
            name='lis_person_name_given',
            field=models.CharField(blank=True, default=None, help_text=b'Example: Billy Bob', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourseenrollment',
            name='lis_person_sourcedid',
            field=models.CharField(blank=True, default=None, help_text=b'Example: _tonn_test5', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourseenrollment',
            name='lti_user_id',
            field=models.CharField(help_text=b'User ID provided by . Example: ab3e190fae668d925d007d79219fbfce90afba6d', max_length=255),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourseenrollmentgrades',
            name='section_url',
            field=models.URLField(help_text=b'Open edX Course Assignment', max_length=255),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourseenrollmentgrades',
            name='synched',
            field=models.DateTimeField(blank=True, help_text=b'The timestamp when this grade record was successfully posted to Willo Grade Sync.', null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourseenrollmentgrades',
            name='usage_key',
            field=opaque_keys.edx.django.models.UsageKeyField(help_text=b'Open edX Block usage key pointing to the homework problem that was graded, invoking the post_grades() api.', max_length=255),
        ),
    ]
