# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-04 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_consumers', '0003_auto_20200227_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ltiexternalcourseenrollmentgrades',
            options={'verbose_name': 'LTI External Course Enrollment Grades', 'verbose_name_plural': 'LTI External Course Enrollment Grades'},
        ),
        migrations.AddField(
            model_name='ltiexternalcourseassignments',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text=b'The Rover assignment due date.', null=True),
        ),
    ]
