# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-04-30 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_consumers', '0004_auto_20200304_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltiexternalcourse',
            name='enabled',
            field=models.BooleanField(default=False, help_text=b'True if grade results for this course should be posted to Willo Labs Grade Sync API.'),
        ),
    ]
