# Generated by Django 2.2.13 on 2020-08-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_consumers', '0008_juniper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltiexternalcourseenrollment',
            name='custom_user_login_id',
            field=models.CharField(blank=True, default=None, help_text='Login ID provided to LTI Consumer. Example: rover_student', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourseenrollment',
            name='ext_roles',
            field=models.CharField(blank=True, default=None, help_text='User permitted roles in external system. Example: urn:lti:instrole:ims/lis/Student,urn:lti:role:ims/lis/Learner,urn:lti:sysrole:ims/lis/User', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ltiexternalcourseenrollment',
            name='lis_person_contact_email_primary',
            field=models.EmailField(help_text='Example: rover_student@willolabs.com', max_length=254, null=True),
        ),
    ]
