# Generated by Django 2.2.13 on 2020-08-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_consumers', '0009_auto_20200804_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltiinternalcourse',
            name='lti_external_course_key1',
            field=models.CharField(blank=True, help_text='Optional LTI tpa_params value used to uniquely identify a course run.', max_length=255),
        ),
        migrations.AddField(
            model_name='ltiinternalcourse',
            name='lti_external_course_key2',
            field=models.CharField(blank=True, help_text='Optional LTI tpa_params value used to uniquely identify a course run.', max_length=255),
        ),
        migrations.AddField(
            model_name='ltiinternalcourse',
            name='lti_external_course_key3',
            field=models.CharField(blank=True, help_text='Optional LTI tpa_params value used to uniquely identify a course run.', max_length=255),
        ),
        migrations.AddField(
            model_name='ltiinternalcourse',
            name='matching_function',
            field=models.CharField(choices=[('CALSTATELA', 'Cal State LA'), ('KU', 'KU'), ('UBC', 'UBC'), ('SWTS', 'SW Texas State')], default='TPA_NEXT', max_length=25),
        ),
    ]
