# Generated by Django 2.2.13 on 2020-08-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_consumers', '0010_auto_20200813_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltiexternalcourseenrollment',
            name='lis_course_offering_sourcedid',
            field=models.CharField(blank=True, help_text='External course section identifier. Example: 2209-90086', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ltiexternalcourseenrollment',
            name='lti_user_image_url',
            field=models.CharField(blank=True, help_text='User profile image url from host LMS. Example: https://calstatela.instructure.com/images/thumbnails/2646143/dudwvMf0hrOrX6TEde9npjTCo9r1MbYVMKUKQVOI', max_length=255),
        ),
        migrations.AlterField(
            model_name='ltiinternalcourse',
            name='matching_function',
            field=models.CharField(choices=[('TPA_NEXT', 'TPA Next URL'), ('CALSTATELA', 'Cal State LA'), ('KU', 'KU'), ('UBC', 'UBC'), ('SWTS', 'SW Texas State')], default='TPA_NEXT', max_length=25),
        ),
    ]
