# Generated by Django 2.2.13 on 2020-08-20 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0022_courseoverviewtab_is_hidden'),
        ('lti_consumers', '0011_auto_20200814_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltiinternalcourse',
            name='course_fk',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_overviews.CourseOverview', unique=True),
        ),
        migrations.AlterField(
            model_name='ltiinternalcourse',
            name='matching_function',
            field=models.CharField(choices=[('TPA_NEXT', 'TPA Next URL'), ('CALSTATELA', 'Cal State LA'), ('KU', 'KU'), ('UBC', 'UBC'), ('STX', 'South Texas')], default='TPA_NEXT', max_length=25),
        ),
        #migrations.AlterUniqueTogether(
        #    name='ltiinternalcourse',
        #    unique_together={('lti_external_course_key1', 'lti_external_course_key2', 'lti_external_course_key3')},
        #),
    ]
