# Generated by Django 2.2.13 on 2020-08-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lti_consumers', '0012_auto_20200820_2240'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ltiinternalcourse',
            unique_together=set(),
        ),
    ]
